# Generated by Django 5.2.6 on 2025-09-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cpf_cliente',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
    ]
